---
- hosts: localhost

  tasks:
    - name: build the image
      command: docker build -t webapp:latest -f /bitnami/jenkins/home/workspace/Maven_Ansible_selenium_Docker/Dockerfile
      args:
       chdir: /bitnami/jenkins/home/workspace/Maven_Ansible_selenium_Docker
    - name: stop existing container
      command: docker stop test_server-webapp
      ignore_errors: yes
    - name: remove existing container
      command: docker rm test_server-webapp
      ignore_errors: yes
    - name: remove existing image
      command: docker rmi saradadocker/webapp:latest
      ignore_errors: yes
    - name: create container
      command: docker run -d --name test_server-webapp -p 8085:8080 saradadocker/webapp:latest
